#!/bin/bash
total=0
while $(expr $# > 0)
do
	i=${1}
	val=$(find . -name "*.$i" -exec cat {} \;| wc -l)
	echo $val" lignes de codes "$i
	total=$(expr $val + $total)
	shift
done
echo "total: "$total
exit 0
